model:
  model_name: ASRLLM
  file: models/model.py:ASRLLM
  llm_model_name: llama3.2-1B
  llm_model: meta-llama/Llama-3.2-1B
  llm_model_path: null
  llm_type: decoder_only
  llm_dim: 2048
  encoder_model_name: whisper-base
  encoder_model: openai/whisper-base
  encoder_ds_rate: 2
  encoder_model_path: null
  encoder_dim: 512
  encoder_projector: linear
  encoder_projector_ds_rate: 8
  modal: audio
  normalize: false
  encoder_type: finetune

train:
  model_name: ASRLLM
  run_validation: true
  batch_size: 20
  batching_strategy: packing
  context_length: 256
  gradient_accumulation_steps: 2      # effective batch ≈ 40
  grad_clip: 1.0
  num_epochs: 3
  num_workers: 8
  warmup_steps: 600
  total_steps: 12000
  validation_interval: 600
  lr: 1.0e-4
  weight_decay: 0.01
  gamma: 0.85
  seed: 42
  use_fp16: false
  mixed_precision: true
  val_batch_size: 28

  use_peft: false
  output_dir: outputs_tiny_clean100/
  freeze_layers: false
  num_freeze_layers: 0
  quantization: false
  one_gpu: true
  save_model: true
  use_fast_kernels: false
  freeze_llm: true
  freeze_encoder: true

data:
  dataset: speech_dataset
  file: datamodules/datasets.py:get_speech_dataset
  train_data_path: data/train-clean-100.jsonl
  val_data_path: data/dev-clean.jsonl
  test_data_path: data/test-clean.jsonl
  train_split: train
  val_split: val
  test_split: test
  prompt: null
  data_path: null
  max_words: null
  max_mel: null
  fix_length_audio: -1
  inference_mode: false
  input_type: mel
  mel_size: 80
  normalize: false

log:
  use_wandb: true
  wandb_dir: ./wandb
  wandb_entity_name: ASRLLM_small
  wandb_project_name: ASRLLM_small
  wandb_exp_name: exp_llama32_1b_whisper_base_clean100
  log_dir: ./logs
  log_filename: train_tiny_clean100.log
  log_interval: 50
