model:
  file: models/model.py:ASRLLM
  llm_name: tiny-gpt2
  llm_path: sshleifer/tiny-gpt2
  llm_type: decoder_only
  llm_dim: 124
  encoder_name: whisper
  encoder_ds_rate: 2
  encoder_path: openai/whisper-base
  encoder_dim: 1280
  encoder_projector: linear
  encoder_projector_ds_rate: 5
  modal: audio
  normalize: false
  encoder_type: finetune

train:
  model_name: sshleifer/tiny-gpt2
  run_validation: true
  batch_size_training: 2
  batching_strategy: packing
  context_length: 512
  gradient_accumulation_steps: 1
  num_epochs: 1
  num_workers_dataloader: 2
  warmup_steps: 10
  total_steps: 100
  validation_interval: 50
  lr: 5.0e-4
  weight_decay: 0.0
  gamma: 0.85
  seed: 42
  use_fp16: false
  mixed_precision: false
  val_batch_size: 2

  use_peft: false
  output_dir: outputs/tiny_smoke
  freeze_layers: false
  num_freeze_layers: 0
  quantization: false
  one_gpu: true
  save_model: false
  use_fast_kernels: false
  freeze_llm: true
  freeze_encoder: true

data:
  dataset: speech_dataset
  file: datamodules/datasets.py:get_speech_dataset
  val_data_path: data/validation.jsonl
  test_split: test
  prompt: null
  data_path: null
  max_words: null
  max_mel: null
  fix_length_audio: -1
  inference_mode: false
  input_type: mel
  mel_size: 80
  normalize: false

log:
  use_wandb: false
  wandb_dir: ./wandb
  wandb_entity_name: project_name
  wandb_project_name: project_name
  wandb_exp_name: exp_smoke_tiny
  log_file: ./tiny_test.log
  log_interval: 5
